@host = http://localhost:8080

### 회원가입1
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password123",
  "name": "admin"
}

### 회원가입2
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123",
  "name": "test"
}

### 로그인
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password123"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

### 토큰 재발급
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "accessToken": "{{auth_token}}",
  "refreshToken": "{{refresh_token}}"
}

### 그룹 생성
POST {{host}}/groups
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "groupName": "testGroup",
  "nickname": "hello"
}

### 채널 생성
POST {{host}}/groups/839757893646845175/channels
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "channelName": "testChannel",
  "type": "TEXT"
}